// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gift-order/GiftExperience.tsx": () => import("../components/mockups/gift-order/GiftExperience.tsx")
};
